# Generated by Django 3.2.6 on 2021-08-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_utilization', models.CharField(max_length=20)),
                ('timestamp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.CharField(max_length=20)),
                ('free', models.CharField(max_length=20)),
                ('timestamp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.CharField(max_length=20)),
                ('free', models.CharField(max_length=20)),
                ('timestamp', models.CharField(max_length=50)),
            ],
        ),
    ]
